### PR TITLE
Feature/fix inconsistent namings

### LINKED ISSUE #15: Inconsistent property naming on interfaces
#### Describe your issue

I noticed there are cases where the property names of some interfaces use snake case instead of camelCase.

See https://github.com/process-engine/consumer_api_contracts/blob/develop/src/data_models/process_model/process_start_request_payload.ts

I didn't look into all files, but there might be more places affected, so all interfaces in contracts should be checked.

Since the Consumer API is not fully used by other libraries yet, it would be a good opportunity to fix them now, before dozens of usages have to be refactored.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by ElRaptorus**
Closes #15 

## What did you change?

- Remove snake cases from public interfaces and use camelCasing instead.
- Restore some interfaces for the rest settings that were lost somehow. 
- Remove unnecessary tslint overrides for variable namings

## How can others test the changes?

Run the integrationtests.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/133

File: src/rest_settings.ts [hunk 1]
```diff
@@ -1,5 +1,37 @@
-// tslint:disable:typedef
-const params = {
+export interface IUrlParameters {
```
Comment (5ebastianMeier) [inline src/rest_settings.ts]: I think the added interfaces are not needed, since they're basically a duplication of the exports that we have to define anyway.

If you look at https://github.com/process-engine/consumer_api_contracts/blob/develop/src/rest_settings.ts, the constant exports enable IntelliSense to work correctly.

Is there any other reason to keep the interfaces?

Comment (ElRaptorus) [reply src/rest_settings.ts]: Maybe. But if you look closely, you'll see that there aren't any typings there. :slightly_smiling_face: 

Using something like `const params: {[name: string]: string | object}` let to build errors, because TSLint couldn't locate the individual url or param names inside `params` and `paths`.
